openapi: 3.0.3
info:
  version: 1.0.0
  title: Account Management API
  description: API REST pour la gestion des comptes utilisateurs, rôles et authentification.
  license:
    name: Proprietary
    url: https://redocly.com/docs/cli/rules/oas/info-license-strict
servers:
  - url: /api/accounts/v1

security:
  - bearerAuth: []

paths:
  /auth/register:
    post:
      operationId:
        creerUtilisateur
      tags:
        - auth_v1
      summary: Créer un nouvel utilisateur
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreationUtilisateur'
      responses:
        '201':
          description: Utilisateur créé avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Utilisateur'
        '400':
          description: Données invalides
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erreur'
        '500':
          description: Erreur interne du serveur
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erreur'

  /auth/login:
    post:
      operationId:
        connecterUtilisateur
      tags:
        - auth_v1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConnectionUtilisateur'
      summary: Connexion d'un utilisateur
      responses:
        '200':
          description: Connexion réussie
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthReponse'
        '401':
          description: Identifiants invalides
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erreur'
        '500':
          description: Erreur interne du serveur
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erreur'

  /users:
    get:
      operationId:
        listerUtilisateurs
      tags:
        - users_v1
      summary: Lister tous les utilisateurs. Cette opération est réservée aux administrateurs.
      responses:
        '200':
          description: Liste des utilisateurs récupérée
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Utilisateur'
        '400':
          description: Données invalides
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erreur'
        '500':
          description: Erreur interne du serveur
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erreur'

  /user/{email}:
    get:
      operationId:
        rechercherUtilisateur
      tags:
        - users_v1
      summary: Rechercher un utilisateur par email
      parameters:
        - name: email
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/Email'
      responses:
        '200':
          description: Informations de l'utilisateur récupérées
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Utilisateur'
        '404':
          description: Utilisateur non trouvé
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erreur'

    put:
      operationId:
        modifierUtilisateur
      tags:
        - users_v1
      summary: Mettre à jour un utilisateur
      parameters:
        - name: email
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/Email'
      responses:
        '200':
          description: Utilisateur mis à jour
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Utilisateur'
        '400':
          description: Données invalides
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erreur'
        '404':
          description: Utilisateur non trouvé
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erreur'

  /roles:
    get:
      operationId:
        listerRoles
      tags:
        - roles_v1
      summary: Lister tous les rôles disponibles
      responses:
        '200':
          description: Liste des rôles récupérée
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Role'
        '400':
          description: Données invalides
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erreur'
        '500':
          description: Erreur interne du serveur
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erreur'
    post:
      operationId:
        creerRole
      tags:
        - roles_v1
      summary: Créer un nouveau rôle
      responses:
        '201':
          description: Rôle créé avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Role'
        '400':
          description: Données invalides
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erreur'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:

    Utilisateur:
      type: object
      properties:
        id:
          type: integer
          example: 1
        email:
          $ref: '#/components/schemas/Email'
        firstName:
          type: string
          example: "Jean"
        lastName:
          type: string
          example: "Dupont"
        active:
          type: boolean
          example: true
        roles:
          type: array
          items:
            $ref: '#/components/schemas/Role'

    CreationUtilisateur:
      type: object
      required:
        - email
        - password
        - firstName
        - lastName
      properties:
        email:
          $ref: '#/components/schemas/Email'
        password:
          type: string
          format: password
          minLength: 8
          example: "Str0ng@Pass!"
        firstName:
          type: string
          example: "Jean"
        lastName:
          type: string
          example: "Dupont"
    
    Role:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: "ADMIN"
        description:
          type: string
          example: "Accès complet à l'application"

    Email:
      type: string
      format: email
      example: "user@example.com"

    ConnectionUtilisateur:
      type: object
      properties:
        email:
          $ref: '#/components/schemas/Email'
        username:
          type: string
          format: password

    AuthReponse:
      type: object
      properties:
        accessToken:
          type: string
          example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9"
        refreshToken:
          type: string
          example: "dGhpc2lzdGhlcmVmcmVzaHRva2Vu"
        tokenType:
          type: string
          example: "Bearer"
        expiresIn:
          type: integer
          example: 3600

    Erreur:
      type: object
      properties:
        status:
          type: string
          example: "error"
        httpStatus:
          type: integer
          example: 500
          description: Code HTTP de l'erreur # Ajouté pour faciliter le diagnostic
        message:
          type: string
          example: "Une erreur inattendue s'est produite."
        timestamp:
          type: string
          format: date-time
          example: "2025-10-08T12:34:56Z"
          description: Date et heure de l'erreur # Ajouté pour traçabilité temporelle
        path:
          type: string
          example: "/api/users/42"
          description: Endpoint appelé lors de l'erreur # Ajouté pour savoir quelle route a échoué
        traceId:
          type: string
          example: "b7e6a4cd9a8b"
          description: Identifiant unique pour suivre la requête # Ajouté pour corrélation dans les logs
        errorCode:
          type: string
          example: "USR_001"
          description: Code d'erreur spécifique à l'application # Ajouté pour distinguer les cas d'erreurs applicatives
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ObjetErreur'

    ObjetErreur:
      type: object
      properties:
        exception:
          type: string
        systemId:
          type: string
        code:
          type: string
        systemName:
          type: string
        meta:
          type: object
          properties: {}
        detail:
          type: string
        time:
          type: string
        message:
          type: string
