openapi: 3.0.3
info:
  version: 1.0.0
  title: API de gestion de compte
  description: API REST pour la gestion des comptes, utilisateurs, rôles et authentification.
  license:
    name: Proprietary
servers:
  - url: /api/comptes/v1

security:
  - bearerAuth: []

paths:
  /auth/register/usager:
    post:
      security: [ ]
      operationId: creerUtilisateur
      tags:
        - auth_v1
      summary: Créer un utilisateur
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreationUtilisateurRequete'
      responses:
        '201':
          description: Utilisateur créé avec succès.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Utilisateur'
        '400':
          description: Données invalides.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erreur'
        '500':
          description: Erreur interne du serveur.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erreur'

  /auth/register/compte:
    post:
      security: [ ]
      operationId: creerCompte
      tags:
        - auth_v1
      summary: Créer un compte
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreationCompteRequete'
      responses:
        '201':
          description: Compte créé avec succès.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Compte'
        '400':
          description: Données invalides.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erreur'
        '500':
          description: Erreur interne du serveur.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erreur'

  /auth/login:
    post:
      security: [ ]
      operationId: connecterUtilisateur
      tags:
        - auth_v1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConnectionRequete'
      summary: Connexion d'un utilisateur
      responses:
        '201':
          description: Connexion réussie.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthReponse'
        '401':
          description: Identifiants invalides.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erreur'
        '500':
          description: Erreur interne du serveur.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erreur'

  /comptes/{id}:
    patch:
      operationId: modifierCompte
      tags:
        - comptes_v1
      summary: Mettre à jour un compte
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ModifierCompteRequete'
      responses:
        '200':
          description: Compte mis à jour.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Compte'
        '400':
          description: Données invalides.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erreur'
        '401':
          description: Identifiants invalides.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erreur'
        '403':
          description: Accès refusé.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erreur'
        '404':
          description: Utilisateur non trouvé.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erreur'
        '500':
          description: Erreur interne du serveur.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erreur'
    get:
      operationId: rechercherCompte
      tags:
        - comptes_v1
      summary: Rechercher un compte par ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: Compte trouvé.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Compte'
        '401':
          description: Identifiants invalides.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erreur'
        '403':
          description: Accès refusé.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erreur'
        '400':
          description: Données invalides.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erreur'
        '500':
          description: Erreur interne du serveur.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erreur'
    delete:
      operationId: supprimerCompte
      tags:
        - comptes_v1
      summary: Supprimer un compte
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 1
      responses:
        '204':
          description: Compte supprimé.
        '401':
          description: Identifiants invalides.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erreur'
        '403':
          description: Accès refusé.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erreur'
        '400':
          description: Données invalides.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erreur'
        '500':
          description: Erreur interne du serveur.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erreur'

  /usagers/{id}:
    patch:
      operationId: modifierUtilisateur
      tags:
        - usagers_v1
      summary: Mettre à jour un utilisateur
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ModifierUtilisateurRequete'
      responses:
        '200':
          description: Utilisateur mis à jour.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Utilisateur'
        '400':
          description: Données invalides.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erreur'
        '401':
          description: Identifiants invalides.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erreur'
        '403':
          description: Accès refusé.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erreur'
        '404':
          description: Utilisateur non trouvé.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erreur'
        '500':
          description: Erreur interne du serveur.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erreur'
    get:
      operationId: rechercherUtilisateur
      tags:
        - usagers_v1
      summary: Rechercher un utilisateur par ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: Utilisateur trouvé.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Utilisateur'
        '400':
          description: Données invalides.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erreur'
        '401':
          description: Identifiants invalides.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erreur'
        '403':
          description: Accès refusé.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erreur'
        '404':
          description: Utilisateur non trouvé.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erreur'
        '500':
          description: Erreur interne du serveur.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erreur'
    delete:
      operationId: supprimerUtilisateur
      tags:
        - usagers_v1
      summary: Supprimer un utilisateur par ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 1
      responses:
        '204':
          description: Utilisateur supprimé.
        '400':
          description: Données invalides.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erreur'
        '401':
          description: Identifiants invalides.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erreur'
        '403':
          description: Accès refusé.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erreur'
        '404':
          description: Utilisateur non trouvé.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erreur'
        '500':
          description: Erreur interne du serveur.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erreur'

  /roles:
    get:
      operationId: listerRoles
      tags:
        - roles_v1
      summary: Lister tous les rôles disponibles
      responses:
        '200':
          description: Liste des rôles récupérée.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Role'
        '400':
          description: Données invalides.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erreur'
        '401':
          description: Identifiants invalides.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erreur'
        '403':
          description: Accès refusé.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erreur'
        '500':
          description: Erreur interne du serveur.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erreur'
    post:
      operationId: creerRole
      tags:
        - roles_v1
      summary: Créer un nouveau rôle
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreationRoleRequete'
      responses:
        '201':
          description: Rôle créé avec succès.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Role'
        '400':
          description: Données invalides.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erreur'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Utilisateur:
      type: object
      properties:
        id:
          type: integer
          example: 1
        email:
          $ref: '#/components/schemas/Email'
        firstName:
          type: string
          example: "Jean"
        lastName:
          type: string
          example: "Dupont"
        active:
          type: boolean
          example: true
        compte:
          $ref: '#/components/schemas/Compte'
        administrateur:
          type: boolean
          example: false
        roles:
          type: array
          items:
            $ref: '#/components/schemas/Role'
    Compte:
      type: object
      properties:
        id:
          type: integer
          example: 1
        nom:
          type: string
          example: "Nom du compte"
        application:
          type: string
          example: "application pour lequel le compte a été créé"
        status:
          type: string
          example: "ACTIF"
        contact:
          $ref: '#/components/schemas/Contact'
    CreationCompteRequete:
      type: object
      required:
        - nom
        - contact
      properties:
        nom:
          type: string
          example: "Nom du compte"
        contact:
          $ref: '#/components/schemas/Contact'
    CreationUtilisateurRequete:
      type: object
      required:
        - email
        - firstName
        - lastName
        - motDePasse
      properties:
        email:
          $ref: '#/components/schemas/Email'
        firstName:
          type: string
          example: "Jean"
        lastName:
          type: string
          example: "Dupont"
        motDePasse:
          $ref: '#/components/schemas/MotDePasse'
    ModifierCompteRequete:
      type: object
      properties:
        nom:
          type: string
          example: "Nom du compte"
        contact:
          $ref: '#/components/schemas/Contact'
    ModifierUtilisateurRequete:
      type: object
      properties:
        email:
          $ref: '#/components/schemas/Email'
        firstName:
          type: string
          example: "Jean"
        lastName:
          type: string
          example: "Dupont"
        motDePasse:
          $ref: '#/components/schemas/MotDePasse'

    Role:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: "ADMIN"
        description:
          type: string
          example: "Accès complet à l'application"

    CreationRoleRequete:
      type: object
      required:
          - name
      properties:
        name:
          type: string
          example: "ADMIN"
        description:
          type: string
          example: "Accès complet à l'application"

    Contact:
      type: object
      properties:
        telephone:
          $ref: '#/components/schemas/Telephone'
        email:
          $ref: '#/components/schemas/Email'
        adresse:
          $ref: '#/components/schemas/Adresse'

    Telephone:
      type: object
      properties:
        indicatif:
          type: string
          example: "+52"
          description: "Indicatif du pays (ex: +52 pour le Mexique)."
        numero:
          type: string
          example: "1234567890"
          description: "Numero de telephone."
    Adresse:
      type: object
      required:
        - rue
        - ville
        - codePostal
      properties:
        rue:
          type: string
          example: "123 Rue Principale"
        ville:
          type: string
          example: "Paris"
        codePostal:
          type: string
          example: "75001"

    Email:
      type: string
      format: email
      example: "user@example.com"

    MotDePasse:
      type: string
      format: password
      minLength: 8
      example: "Str0ng@Pass!"

    ConnectionRequete:
      type: object
      required:
          - email
          - motDePasse
      properties:
        email:
          $ref: '#/components/schemas/Email'
        motDePasse:
          $ref: '#/components/schemas/MotDePasse'

    AuthReponse:
      type: object
      properties:
        accessToken:
          type: string
          example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9"
        refreshToken:
          type: string
          example: "dGhpc2lzdGhlcmVmcmVzaHRva2Vu"
        tokenType:
          type: string
          example: "Bearer"
        expiresIn:
          type: integer
          example: 3600

    Erreur:
      type: object
      properties:
        status:
          type: string
          example: "error"
        httpStatus:
          type: integer
          example: 500
          description: Code HTTP de l'erreur
        message:
          type: string
          example: "Une erreur inattendue s'est produite."
        timestamp:
          type: string
          format: date-time
          example: "2025-10-08T12:34:56Z"
          description: Date et heure de l'erreur
        path:
          type: string
          example: "/api/accounts/v1/"
          description: Endpoint appelé lors de l'erreur
        traceId:
          type: string
          example: "b7e6a4cd9a8b"
          description: Identifiant unique pour suivre la requête
        errorCode:
          type: string
          example: "USR_001"
          description: Code d'erreur spécifique à l'application
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ObjetErreur'

    ObjetErreur:
      type: object
      properties:
        exception:
          type: string
        systemId:
          type: string
        code:
          type: string
        systemName:
          type: string
        meta:
          type: object
          properties: {}
        detail:
          type: string
        time:
          type: string
        message:
          type: string
